ssl_monitor:
  urls:
    - "https://example.com"
    - "https://google.com"
  interval: 3600
  webhook: "https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXX"
  username: SSLMonitor
  avatar_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png
  allow_self_signed: false
  cert_expiry_threshold: 10